# Generated by Django 4.0.3 on 2022-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='release_date',
            field=models.DateField(verbose_name='Дата: YYYY-MM-dd'),
        ),
    ]
